// frontend-angular/src/app/app.ts
import { Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize } from 'rxjs';

import { JOB_STATUS_OPTIONS, Job, JobStatus } from './job.model';
import { JobsApi } from './jobs-api';

type Notice = {
  type: 'success' | 'error';
  text: string;
};

@Component({
  selector: 'app-root',
  imports: [ReactiveFormsModule],
  templateUrl: './app.html',
  styleUrl: './app.css'
})
export class App {
  private readonly jobsApi = inject(JobsApi);
  private readonly formBuilder = inject(FormBuilder);

  protected readonly statusOptions = JOB_STATUS_OPTIONS;
  protected readonly jobs = signal<Job[]>([]);
  protected readonly notice = signal<Notice | null>(null);
  protected readonly isLoading = signal(true);
  protected readonly isSaving = signal(false);
  protected readonly editingJobId = signal<number | null>(null);
  protected readonly deletingJobId = signal<number | null>(null);
  protected readonly updatingJobIds = signal<number[]>([]);

  protected readonly totals = computed(() => {
    const jobs = this.jobs();

    return {
      saved: jobs.filter((job) => job.status === 'Saved').length,
      applied: jobs.filter((job) => job.status === 'Applied').length,
      interviewing: jobs.filter((job) => job.status === 'Interviewing').length,
      offers: jobs.filter((job) => job.status === 'Offer').length,
    };
  });

  protected readonly jobForm = this.formBuilder.nonNullable.group({
    company: ['', Validators.required],
    position: ['', Validators.required],
    status: this.formBuilder.nonNullable.control<JobStatus>('Saved', Validators.required),
  });

  protected readonly editForm = this.formBuilder.nonNullable.group({
    company: ['', Validators.required],
    position: ['', Validators.required],
  });

  constructor() {
    this.loadJobs();
  }

  protected addJob(): void {
    if (this.jobForm.invalid || this.isSaving()) {
      this.jobForm.markAllAsTouched();
      return;
    }

    this.notice.set(null);
    this.isSaving.set(true);

    this.jobsApi.createJob(this.jobForm.getRawValue()).pipe(
      finalize(() => this.isSaving.set(false)),
    ).subscribe({
      next: (job) => {
        this.jobs.update((jobs) => [job, ...jobs]);
        this.notice.set({ type: 'success', text: `${job.position} at ${job.company} was added.` });
        this.jobForm.reset({ company: '', position: '', status: 'Saved' });
      },
      error: () => this.notice.set({ type: 'error', text: 'Failed to add job.' }),
    });
  }

  protected startEditing(job: Job): void {
    this.editingJobId.set(job.id);
    this.editForm.setValue({ company: job.company, position: job.position });
  }

  protected cancelEditing(): void {
    this.editingJobId.set(null);
    this.editForm.reset({ company: '', position: '' });
  }

  protected saveDetails(jobId: number): void {
    if (this.editForm.invalid) {
      this.editForm.markAllAsTouched();
      return;
    }

    this.notice.set(null);
    this.markUpdating(jobId);

    this.jobsApi.updateJobDetails(jobId, this.editForm.getRawValue()).pipe(
      finalize(() => this.unmarkUpdating(jobId)),
    ).subscribe({
      next: (updatedJob) => {
        this.replaceJob(updatedJob);
        this.notice.set({ type: 'success', text: 'Job details updated.' });
        this.cancelEditing();
      },
      error: () => this.notice.set({ type: 'error', text: 'Failed to update job details.' }),
    });
  }

  protected updateStatus(jobId: number, status: string): void {
    this.notice.set(null);
    this.markUpdating(jobId);

    this.jobsApi.updateJobStatus(jobId, status as JobStatus).pipe(
      finalize(() => this.unmarkUpdating(jobId)),
    ).subscribe({
      next: (updatedJob) => {
        this.replaceJob(updatedJob);
        this.notice.set({ type: 'success', text: 'Job status updated.' });
      },
      error: () => this.notice.set({ type: 'error', text: 'Failed to update job status.' }),
    });
  }

  protected deleteJob(jobId: number): void {
    if (!window.confirm('Delete this job?')) {
      return;
    }

    this.notice.set(null);
    this.deletingJobId.set(jobId);

    this.jobsApi.deleteJob(jobId).pipe(
      finalize(() => this.deletingJobId.set(null)),
    ).subscribe({
      next: () => {
        this.jobs.update((jobs) => jobs.filter((job) => job.id !== jobId));
        this.notice.set({ type: 'success', text: 'Job deleted.' });
      },
      error: () => this.notice.set({ type: 'error', text: 'Failed to delete job.' }),
    });
  }

  protected isUpdating(jobId: number): boolean {
    return this.updatingJobIds().includes(jobId);
  }

  private loadJobs(): void {
    this.jobsApi.getJobs().pipe(
      finalize(() => this.isLoading.set(false)),
    ).subscribe({
      next: (jobs) => this.jobs.set(jobs),
      error: () => this.notice.set({ type: 'error', text: 'Failed to load jobs from .NET API.' }),
    });
  }

  private replaceJob(updatedJob: Job): void {
    this.jobs.update((jobs) => jobs.map((job) => job.id === updatedJob.id ? updatedJob : job));
  }

  private markUpdating(jobId: number): void {
    this.updatingJobIds.update((ids) => ids.includes(jobId) ? ids : [...ids, jobId]);
  }

  private unmarkUpdating(jobId: number): void {
    this.updatingJobIds.update((ids) => ids.filter((id) => id !== jobId));
  }
}

// frontend/src/App.jsx
import { useEffect, useState } from "react";
import "./App.css";
import JobCard from "./components/JobCard";
import JobForm from "./components/JobForm";
import { createJob, getJobs, updateJobStatus, updateJobDetails, deleteJob } from "./services/jobsApi";

function App() {
  const [jobs, setJobs] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [deletingJobId, setDeletingJobId] = useState(null);
  const [updatingJobIds, setUpdatingJobIds] = useState([]);
  const [message, setMessage] = useState("");

  useEffect(() => {
    async function loadJobs() {
      try {
        setJobs(await getJobs());
      } catch {
        setMessage({
          type: "error",
          text: `Failed to load jobs.`,
        });
      } finally {
        setIsLoading(false);
      }
    }

    loadJobs();
  }, []);

  async function handleCreateJob(job) {
    setMessage("");
    setIsSaving(true);

    try {
      const newJob = await createJob(job);
      setJobs((currentJobs) => [...currentJobs, newJob]);

      setMessage({
        type: "success",
        text: `${newJob.position} at ${newJob.company} was added.`,
      });
    } catch (error) {
      setMessage({
        type: "error",
        text: `Failed to add ${job.position} at ${job.company}.`,
      });
      throw error;
    } finally {
      setIsSaving(false);
    }
  }

  async function handleDeleteJob(jobId) {
    if (!window.confirm("Delete this job?")) return;

    setMessage("");
    setDeletingJobId(jobId);

    try {
      await deleteJob(jobId);

      setJobs((currentJobs) =>
        currentJobs.filter((job) => job.id !== jobId)
      );
      setMessage({
        type: "success",
        text: `Job deleted successfully.`,
      });
    } catch {
      setMessage({
        type: "error",
        text: `Failed to delete job.`,
      });
    } finally {
      setDeletingJobId(null);
    }
  }

  async function handleStatusChange(jobId, status) {
    setMessage("");
    setUpdatingJobIds((currentIds) => [...currentIds, jobId]);

    try {
      await updateJobStatus(jobId, status);
      setJobs((currentJobs) =>
        currentJobs.map((job) =>
          job.id === jobId ? { ...job, status } : job,
        ),
      );
      setMessage({
        type: "success",
        text: `Job status updated successfully.`,
      });
    } catch {
      setMessage({
        type: "error",
        text: `Failed to update job status.`,
      });
    } finally {
      setUpdatingJobIds((currentIds) => currentIds.filter((id) => id !== jobId));
    }
  }

  async function handleUpdateJobDetails(jobId, details) {
    setMessage("");
    setUpdatingJobIds((currentIds) => [...currentIds, jobId]);

    try {
      await updateJobDetails(jobId, details);
      setJobs((currentJobs) =>
        currentJobs.map((job) =>
          job.id === jobId ? { ...job, ...details } : job,
        ),
      );
      setMessage({
        type: "success",
        text: `Job details updated successfully.`,
      });
    } catch {
      setMessage({
        type: "error",
        text: `Failed to update job details.`,
      });
    } finally {
      setUpdatingJobIds((currentIds) => currentIds.filter((id) => id !== jobId));
    }
  }

  return (
    <main>
      <h1>Job Tracker</h1>

      <JobForm onCreateJob={handleCreateJob} isSaving={isSaving} />
      {message && <p className={`message ${message.type}`}>{message.text}</p>}

      {isLoading ? (
        <p>Loading jobs...</p>
      ) : jobs.length === 0 ? (
        <p>No jobs yet. Add your first job above.</p>
      ) : (
        <section className="job-list">
          {jobs.map((job) => (
            <JobCard
              key={job.id}
              job={job}
              onStatusChange={handleStatusChange}
              onUpdateDetails={handleUpdateJobDetails}
              onDelete={handleDeleteJob}
              isDeleting={deletingJobId === job.id}
              isUpdating={updatingJobIds.includes(job.id)}
            />
          ))}
        </section>
      )}
    </main>
  );
}

export default App;
